//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Jabber-Net library")]
[assembly: AssemblyDescription("Connect to Jabber (http://www.jabber.org/) from .Net")]
[assembly: AssemblyCompany("Cursive Systems, Inc.")]
[assembly: AssemblyProduct("jabber-net")]
[assembly: AssemblyCopyright("Copyright (c) Cursive, Inc. 2000-2007")]
[assembly: AssemblyVersion("2.0.0.553")]
[assembly: AssemblyDelaySign(false)]
[assembly: CLSCompliant(true)]
[assembly: AssemblyKeyFile("../../jabbernet.key")]


